### PR TITLE
adding new Bing Image API C# quickstart

### PR DESCRIPTION
**Pull request by aahill**
## Purpose

* ...
This is an updated quickstart for Bing Image Search, to compliment the upcoming documentation changes on docs.microsoft.com

## Does this introduce a breaking change?

```
[ ] Yes
[ x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [https://github.com/aahill/cognitive-services-dotnet-sdk-samples.git]
cd [cognitive-services-dotnet-sdk-samples\BingSearchv7\BingImageSearch\quickstart]
git checkout [dotnet-sdk-quickstart]
run the C# code
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...
That the code prints out a URL from the Bing Image Search API.

### CODE REVIEW

**Comment by MikeDodaro** [comment]
#sign-off

**Comment by aahill** [comment]
@mohabghanem, would you be able to merge this file in, or know who could? This is a new code sample to support some upcoming documentation changes on docs.microsoft.com. Thanks!

**Comment by mohabghanem** [comment]
@yangyuan , Can you help @aahill ?

**Comment by yangyuan** [comment]
@aahill @mohabghanem done

**Pull request merged**
