### PR TITLE
[CustomVision] Don't open the file twice.

### PR DESCRIPTION
**Pull request by areddish**
## API Name (Kind)
CustomVision

## Purpose
Predicting an image is opening the file twice, updating code to only open the file once.

## Other Information
Fixes MicrosoftDocs/azure-docs#46887

### CODE REVIEW

**Comment by GiftA-MSFT** [comment]
#sign-off

**Comment by GiftA-MSFT** [comment]
@areddish can you please review and approve this PR? Thanks.

**Comment by diberry** [comment]
@erhopf @nitinme

**Comment by erhopf** [comment]
@PatrickFarley - Can you take a look at this PR?

**Comment by GiftA-MSFT** [comment]
#sign-off

**Comment by PatrickFarley** [comment]
#sign-off

**Comment by PatrickFarley** [comment]
@yangyuan Please merge this PR, thank you!

**Pull request merged**
